project:
  type: website
  output-dir: _site

website:
  title: "Multiome Sleep Deprivation"
  open-graph:
     locale:
       en_US
     site-name:
       "Multiome Sleep"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Articles"
        menu:
        - text: "05 DEGs Wild Type"
          href: vignettes/v05_DE.html
        - text: "06 DEGs Wild Type CA1-do"
          href: vignettes/v06_DE_CA1Do.html
        - text: "07 DARs Wild Type CA1-do"
          href: vignettes/v07_DARs.html
        - text: "09 DEGs Shank3 DeltaC CA1-do"
          href: vignettes/v09_DE_S3_CA1Do.html

format:
  html:
    favicon: mouse.ico
    theme: spacelab
    toc: true
    toc_float: true
    code-fold: true


editor: visual

