project:
  type: website
  output-dir: _site

website:
  title: "Multiome Sleep Deprivation"
  open-graph:
     locale:
       en_US
     site-name:
       "Multiome Sleep"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: v05_DE.qmd
        text: DEGsWT
      - href: v06_DE_CA1Do.qmd
        text: DEGsWTCA1Do
      - href: v07_DARs.qmd
        text: DARsWT_CA1Do
      - about.qmd

format:
  html:
    favicon: mouse.ico
    theme: cosmo
    toc: true
    toc_float: true
    code-fold: true


editor: visual

